name: 'Copy Directory'
description: 'Copy local directories'
inputs:
  source:
    description: 'Source path'
    required: true
  target:
    description: 'Target path'
    required: true
runs: 
  using: "composite"
  args: 
    - ${{inputs.source}}
    - ${{inputs.target}}
  steps:
    - run: ${{ github.action_path }}/copypaste.ps1
      shell: bash
    - run: ${{ github.action_path }}/remove_working_directory.ps1
      shell: bash